#!/bin/bash
MODULE=scala_29/lift_blank
WC_DIR=$OPENSHIFT_DATA_DIR/checkout
TMP=$OPENSHIFT_DATA_DIR/tmp/sbt
TARGET=$OPENSHIFT_DATA_DIR/target

OPENSHIFT_OPTS="-Dsbt.ivy.home=${OPENSHIFT_DATA_DIR}.ivy2/ -Divy.home=${OPENSHIFT_DATA_DIR}.ivy2/ -Dsbt.boot.directory=${OPENSHIFT_DATA_DIR}/.sbt"
JAVA_OPTS="-Djava.io.tmpdir=$TMP"

rm -fr $TMP $TARGET
mkdir -p $TMP $TARGET

cd $WC_DIR/$MODULE
./sbt $JAVA_OPTS $OPENSHIFT_OPTS package
cp target/scala*/*.war $TARGET/root.war
