#!/bin/bash
JETTY_VERSION=9.0.0.v20130308
JETTY_URL="http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/$JETTY_VERSION/$JETTY_RUNNER"
JETTY_RUNNER="jetty-runner-$JETTY_VERSION.jar"

cd $OPENSHIFT_DATA_DIR

[ -f $JETTY_RUNNER ] || wget $JETTY_URL

nohup java -jar $JETTY_RUNNER \
  --port $OPENSHIFT_INTERNAL_PORT \
  --host $OPENSHIFT_INTERNAL_IP \
  --log $OPENSHIFT_DIY_LOG_DIR/request-yyyy_mm_dd.log \
  --out $OPENSHIFT_DIY_LOG_DIR/jetty-yyyy_mm_dd.log \
  --stats unsecure \
  webapps/root.war \
  > $OPENSHIFT_DIY_LOG_DIR/jetty.log 2>&1 &

